# Generated by Django 4.2.7 on 2023-11-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direccion', '0001_initial'),
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_dni', models.CharField(db_column='customer_DNI', max_length=8, unique=True)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_surname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursal.sucursal')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('limite_cajas_ahorro', models.IntegerField()),
                ('limite_cajas_ahorro_pesos', models.IntegerField()),
                ('limite_cajas_ahorro_dolares', models.IntegerField()),
                ('limite_cajas_ahorro_pesos_extra', models.IntegerField()),
                ('limite_cajas_ahorro_dolares_extra', models.IntegerField()),
                ('limite_cuentas_corriente', models.IntegerField()),
                ('limite_cuentas_inversion', models.IntegerField()),
                ('limite_tarjetas_debito', models.IntegerField()),
                ('limite_tarjetas_credito', models.IntegerField()),
                ('limite_extensiones', models.IntegerField()),
                ('limite_credito', models.IntegerField()),
                ('limite_cuota_credito', models.IntegerField()),
                ('master_disponible', models.BooleanField()),
                ('visa_disponible', models.BooleanField()),
                ('amex_disponible', models.BooleanField()),
                ('limite_retiro_mensual', models.IntegerField()),
                ('limite_retiro_diario', models.IntegerField()),
                ('comision_saliente', models.FloatField()),
                ('comision_entrante', models.FloatField()),
                ('limite_chequeras', models.IntegerField()),
            ],
            options={
                'db_table': 'tipo_cliente',
            },
        ),
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('id_direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='direccion.direccion')),
            ],
            options={
                'db_table': 'direccion_cliente',
            },
        ),
    ]
