# Generated by Django 4.2.7 on 2023-12-01 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
