# Generated by Django 4.2.7 on 2023-11-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(db_column='movimiento_id', primary_key=True, serialize=False)),
                ('tipo_operacion', models.CharField(blank=True, max_length=50, null=True)),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='hora')),
            ],
            options={
                'db_table': 'movimientos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Movimientos',
        ),
    ]
