# Generated by Django 4.2.7 on 2023-12-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_pago',
            field=models.DateTimeField(default=None),
        ),
    ]
