# Generated by Django 4.2.7 on 2023-12-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_alter_factura_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
