# Generated by Django 4.2.7 on 2023-11-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'marca_tarjeta',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('DEBITO', 'DEBITO'), ('CREDITO', 'CREDITO')], max_length=7)),
                ('cvv', models.CharField(max_length=3)),
                ('fecha_expiracion', models.DateField()),
                ('fecha_creacion', models.DateField()),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tarjeta.marcatarjeta')),
            ],
            options={
                'db_table': 'tarjeta',
            },
        ),
    ]
