# Generated by Django 4.2.7 on 2023-11-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'managed': True},
        ),
    ]
