# Generated by Django 4.2.7 on 2023-12-03 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0002_delete_auditoriacuenta'),
        ('prestamos', '0002_delete_prestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('monto', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', related_query_name='prestamo', to='cuentas.cuenta')),
            ],
            options={
                'db_table': 'prestamo',
            },
        ),
    ]
