# Generated by Django 4.2.7 on 2023-11-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_number', models.IntegerField()),
                ('branch_name', models.CharField(max_length=50)),
                ('branch_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.direccion')),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
    ]
