# Generated by Django 4.2.7 on 2023-12-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(db_column='branch_id', primary_key=True, serialize=False)),
                ('numero', models.IntegerField(db_column='branch_number')),
                ('nombre', models.CharField(db_column='branch_name', max_length=50)),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
    ]
